export const mainContractAbi = [
    {
        inputs: [
            {
                internalType: "contract IWorldID",
                name: "_worldId",
                type: "address",
            },
            { internalType: "string", name: "_appId", type: "string" },
            { internalType: "string", name: "_actionId", type: "string" },
        ],
        stateMutability: "nonpayable",
        type: "constructor",
    },
    { inputs: [], name: "InvalidNullifier", type: "error" },
    {
        inputs: [
            { internalType: "string", name: "id", type: "string" },
            { internalType: "string", name: "name", type: "string" },
            { internalType: "string", name: "description", type: "string" },
            { internalType: "string", name: "img", type: "string" },
            { internalType: "string", name: "link", type: "string" },
            { internalType: "string", name: "catagory", type: "string" },
        ],
        name: "addProject",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "", type: "address" }],
        name: "contributions",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "getBalance",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "getProjects",
        outputs: [
            {
                components: [
                    { internalType: "string", name: "id", type: "string" },
                    { internalType: "string", name: "name", type: "string" },
                    {
                        internalType: "string",
                        name: "description",
                        type: "string",
                    },
                    { internalType: "string", name: "img", type: "string" },
                    { internalType: "string", name: "link", type: "string" },
                    {
                        internalType: "string",
                        name: "catagory",
                        type: "string",
                    },
                    { internalType: "uint256", name: "votes", type: "uint256" },
                ],
                internalType: "struct Contract.Project[]",
                name: "",
                type: "tuple[]",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "getTotalVotes",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "addr", type: "address" }],
        name: "getVotes",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "string", name: "", type: "string" }],
        name: "ids",
        outputs: [{ internalType: "address", name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "", type: "address" }],
        name: "projectIndexesByAddress",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "totalVotes",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "signal", type: "address" },
            { internalType: "uint256", name: "root", type: "uint256" },
            { internalType: "uint256", name: "nullifierHash", type: "uint256" },
            { internalType: "uint256[8]", name: "proof", type: "uint256[8]" },
        ],
        name: "vote",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "", type: "address" }],
        name: "votes",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
];
